apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - name: deployment-validation.webhook.k8s.io
    rules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["DELETE"]
        resources: ["deployments"]
    clientConfig:
      service:
        name: webhook-server
        namespace: default
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIVENDQWdXZ0F3SUJBZ0lKQU5Dd2R4L1NFcHdQTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ1V4SXpBaEJnTlYKQkFNTUduZGxZbWh2YjJzdGMyVnlkbVZ5TG1SbFptRjFiSFF1YzNaak1CNFhEVEkwTURZd01qQTBORE13TmxvWApEVEkxTURZd01qQTBORE13Tmxvd0pURWpNQ0VHQTFVRUF3d2FkMlZpYUc5dmF5MXpaWEoyWlhJdVpHVm1ZWFZzCmRDNXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzdwQzdIQ0tuZFhiOGcKbGNNdFVnR2FLOUtvSDdYeTA0NWNBVjBYS0Z1bjdNUDZlcmxBNWFETWxTVXV5VjlCOHlrNkQ4Rlp2T0pqeUVWUApxWWtQZTBZUUpkV3RjKzFuRkh6dDZmZEZ4MU5OTDE0bCs0ZEZ6Qm0zdjBqRTZWOTc0OFpZaDU3YVhOR1BKd2NNCnhSb2lIT21BYzJoaHd0Q21Ea0lCeXlqTExNQkNDVGFnbzQ3RHg1eG9vKzBjSmVNYXlvZXB4ZmtwTkpSZDBSTXoKMys0TE0yTHhvZXFoeCtSNGJmc21OWWFUdFdSMzlHaU80dkJNMzlkUUpzbW54S3djcytGTzUvZk04SE1aT2xwagpzQnhRdE1jOUQ2ZHpkSW5nY1loTDFLTmxEMHJmTGcyK0ZEczVTc2puNEdyS3pjRHVZRys5QmVISVFoVkUwc1N0Cm5sNG1KR1BmQWdNQkFBR2pVREJPTUIwR0ExVWREZ1FXQkJUd0YvRStoZFErKzVyMVdOUVdlTmR0aHRxbkxUQWYKQmdOVkhTTUVHREFXZ0JUd0YvRStoZFErKzVyMVdOUVdlTmR0aHRxbkxUQU1CZ05WSFJNRUJUQURBUUgvTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQkFRQzJZaDJWRUR0Ry9pN2NNTVZoRHk2ZVpnMmxqWUxUdXlHK3pXNXhNdnd4Cmw4NnMyQUVSbkU2SjBMY3NFc1NoQml0MDg4NnpFQ3Bra09FeEoxQjVpZVF4SEozbTRZNExmcG16M1h4TU4wbFQKS3ozVXl4cmRnSHI0VHdXNnVtNGNKUmpTZ213UEtIUFdtOHE3aU1qNXVNTlAwZTYvNDZRVWtCa1J0U252Z3FNWQpTY3NhNUViZUZiVk9nWHlIN05haThTWHdIRStYY2VkNnFuS2RUMHZtdGN2QlVKMWUwV2FISW90cDl0aC9CTzgvCnd4M01uSHVNVUcwZStmUDZyZm1YQUdGUCt3STZMM05VcjBtMGc3Vm9ycjdCNGtaMnVaNW1VOFN0Y2xFdUprTFkKMTd5c0Z1RWlvUTVwSUh4amdOUHZJdDhKRExSeUIxOHhTaE1GMjJmb2xIajEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    admissionReviewVersions: ["v1"]
    sideEffects: None
