apiVersion: apps.geray.cn/v1
kind: Application
metadata:
  name: app-nginx
  namespace: default
  labels:
    app: app-nginx
spec:
  # TODO(user): Add fields here
  deployment:
    replicas: 5
    selector:
      matchLabels:
        app: app-nginx
    template:
      metadata:
        labels:
          app: app-nginx
      spec:
        containers:
          - name: nginx
            image: nginx:1.14.2
            ports:
              - containerPort: 80
  service:
    type: NodePort
    ports:
      - port: 80
        targetPort: 80
        nodePort: 30080
